### PR TITLE
New addition of features for the primer validation and rarefaction functions

### PR DESCRIPTION
**Pull request by lemetrec**
Added features and change of the computation of the preprocessing.
Updated the vsearch sort function
Corrected typo in the extract_ends function

### CODE REVIEW

**Comment by zachcp** [comment]
Hey Christophe,


looks like you have  some conflicts with the master branch. Can you rebase against the master branch?

thanks,
zach cp

**Comment by lemetrec** [comment]
Hey Zach,

I just rebased against the master. I am pushing again my new commits. I
hope it won't generate more conflicts.

Thanks
Christophe

2017-01-03 16:04 GMT-05:00 zachcp <notifications@github.com>:

**Comment by zachcp** [comment]
Hi Christophe,

Thanks for the effort. Github is reporting conflicts in the following files:

```
R/extract_ends.R
R/primer-validation-functions.R
```

Can you test that this repo is set as upstream and then run:

```
git fetch upstream master
git rebase upstream/master
```
Thanks,
zach cp

**Comment by lemetrec** [comment]
I've rebased after the fetch and corrected the conflicts. however, my push doesn't seem to go.

**Comment by lemetrec** [comment]
It should work now.

**Pull request merged**
