### PR TITLE
New pull request on improvements over the primer analysis functions and vsearch

### PR DESCRIPTION
**Pull request by lemetrec**

### CODE REVIEW

**Comment by zachcp** [comment]
christophe. is this PR building/testing on your machine?

**Comment by lemetrec** [comment]
It was before I used more as a package, had some issues with my environment
path for the vsearch since, but it is solved. Don't merge just yet, I am
working on a better version right now. Hopefully by end of the day I will
push it.

2016-12-02 11:19 GMT-05:00 zachcp <notifications@github.com>:

**Comment by zachcp** [comment]
ok great.

**Comment by lemetrec** [comment]
I have pushed several new commits. It now works good by just building the
package and executing this:

primer_analysis("PEP", fileList,
"/Users/christophelemetre/Documents/Work/eSNaPD3/PEPSequences.fasta")

I'm now working on a small version of the files so we can add them in data
for testing of the package.

2016-12-02 11:37 GMT-05:00 zachcp <notifications@github.com>:

**Pull request merged**
